let state={config:{},dashboard:{},categories:{},transactions:[],selectedType:'Pemasukan'};
const $=id=>document.getElementById(id);
const rupiah=n=>'Rp '+Number(n||0).toLocaleString('id-ID');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const shortId=id=>{const s=String(id||'');return s.startsWith('TRX-')&&s.length>9?s.slice(0,4)+s.slice(-5):s;};
function toast(m){const e=$('toast');if(!e)return;e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3600)}
function errorToast(e){console.error(e);setDbStatus(false,e?.message||e);toast('❌ '+(e?.message||e))}
function setDbStatus(ok,m){const e=$('connectionStatus');if(!e)return;e.className='connection-pill '+(ok?'online':'offline');e.innerHTML=`<span class="status-icon">${ok?'✓':'!'}</span><span class="status-text">${esc(m||(ok?'Database tersambung':'Database tidak tersambung'))}</span>`}
function navigate(p){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===p));$('page-'+p)?.classList.add('active');$('sidebar')?.classList.remove('open');if(p==='transactions')renderTransactions()}
function setNow(){const d=new Date(),x=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString();$('tanggal').value=x.slice(0,10);$('waktu').value=x.slice(11,16)}
function renderDashboard(){const d=state.dashboard||{};$('saldo').textContent=rupiah(d.saldo);$('pemasukan').textContent=rupiah(d.pemasukan);$('pengeluaran').textContent=rupiah(d.pengeluaran);$('jumlahTransaksi').textContent=Number(d.jumlahTransaksi||0);$('saldoMeta').innerHTML='✓ <b>Server verified</b> · '+new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'});setDbStatus(true,'Database online • server verified');const rows=state.transactions.filter(t=>t.status==='AKTIF').slice(0,8);$('recentTable').innerHTML=tableHtml(rows,false)}
function typeBadge(t){return `<span class="badge ${t==='Pemasukan'?'in':'out'}">${t==='Pemasukan'?'↑':'↓'} ${esc(t)}</span>`}
function tableHtml(rows,actions=true){if(!rows.length)return '<div class="empty">Belum ada transaksi aktif.</div>';return `<table><thead><tr><th>ID</th><th>Tanggal</th><th>Jenis</th><th>Kategori</th><th>Keterangan</th><th>Nominal</th><th>Status</th>${actions?'<th>Aksi</th>':''}</tr></thead><tbody>${rows.map(t=>{const active=t.status==='AKTIF';return `<tr><td><code class="trx-id" title="${esc(t.id)}">${esc(shortId(t.id))}</code></td><td>${esc(t.tanggal)}</td><td>${typeBadge(t.jenis)}</td><td>${esc(t.kategori)}</td><td>${esc(t.keterangan)}</td><td class="${t.jenis==='Pemasukan'?'income':'expense'}">${t.jenis==='Pemasukan'?'+':'−'} ${rupiah(t.nominal)}</td><td>${active?'<span class="badge active">● AKTIF</span>':'<span class="badge cancel">DIBATALKAN</span>'}</td>${actions?`<td>${active?`<button class="btn mini ghost" data-edit="${esc(t.id)}">Edit</button> <button class="btn mini danger" data-cancel="${esc(t.id)}">Batal</button>`:'-'}</td>`:''}</tr>`}).join('')}</tbody></table>`}
function renderCategories(){const list=state.categories?.[state.selectedType]||[];$('kategori').innerHTML='<option value="">Pilih kategori</option>'+list.map(x=>`<option>${esc(x)}</option>`).join('')}
function renderTransactions(){let rows=[...state.transactions],q=$('search').value.trim().toLowerCase(),jenis=$('filterJenis').value,start=$('filterStart').value,end=$('filterEnd').value;rows=rows.filter(t=>(!q||[t.id,t.kategori,t.keterangan,t.catatan].join(' ').toLowerCase().includes(q))&&(!jenis||t.jenis===jenis)&&(!start||t.tanggal>=start)&&(!end||t.tanggal<=end));$('transactionTable').innerHTML=tableHtml(rows,true)}
function openEdit(id){const t=state.transactions.find(x=>String(x.id)===String(id));if(!t)return;$('editId').value=t.id;$('editPassword').value='';$('editReason').value='';$('editFields').innerHTML=`<div class="form-grid"><label>Tanggal<input id="eTanggal" type="date" value="${esc(t.tanggal)}" required></label><label>Waktu<input id="eWaktu" type="time" value="${esc(t.waktu)}" required></label><label>Nominal<input id="eNominal" type="number" value="${Number(t.nominal)}" min="1" required></label><label>Kategori<select id="eKategori">${(state.categories?.[t.jenis]||[]).map(x=>`<option ${x===t.kategori?'selected':''}>${esc(x)}</option>`).join('')}</select></label><label class="full">Keterangan<input id="eKeterangan" value="${esc(t.keterangan)}" required></label><label class="full">Catatan<textarea id="eCatatan">${esc(t.catatan)}</textarea></label></div>`;$('editModal').classList.add('show')}
function openCancel(id){$('cancelId').value=id;$('cancelPassword').value='';$('cancelReason').value='';$('cancelModal').classList.add('show')}
function closeModal(id){$(id).classList.remove('show');$(id).setAttribute('aria-hidden','true')}
async function load(){setDbStatus(false,'Mengambil data terbaru dari server...');try{const data=await KasApi.getInitialData();if(!data||!Array.isArray(data.transactions))throw Error('Server tidak mengirim daftar transaksi yang valid.');state={...state,...data,transactions:data.transactions.map(KasApi.normalizeTransaction)};renderConfig();renderCategories();renderDashboard();renderTransactions()}catch(e){setDbStatus(false,'Database gagal diakses');errorToast(e)}}
function renderConfig(){const c=state.config||{};[['admin_rt','nama_rt'],['admin_rw','nama_rw'],['admin_dukuh','dukuh'],['admin_desa','desa'],['admin_kecamatan','kecamatan'],['admin_kabupaten','kabupaten'],['admin_ketua','ketua_rt'],['admin_bendahara','bendahara'],['admin_saldo','saldo_awal']].forEach(([a,b])=>$(a).value=c[b]??'')}
async function reload(){await load();toast('✓ Data disinkronkan dan diverifikasi dari server.')}
async function buildWhatsAppReport(){const r=await KasApi.getReportSummary();return `*LAPORAN KAS ${r.nama_rt||'RT 01'} ${r.nama_rw||'RW 01'}*\n${[r.dukuh,r.desa].filter(Boolean).join(', ')}\nPer Tanggal: ${r.date}\n\nSaldo Awal: ${rupiah(r.saldoAwal)}\nTotal Pemasukan: ${rupiah(r.pemasukan)}\nTotal Pengeluaran: ${rupiah(r.pengeluaran)}\n-----------------------------------\n*SISA SALDO SEKARANG: ${rupiah(r.saldo)}*\n\nCatatan: Transaksi dicatat secara otomatis via Aplikasi Kas RT.`}
async function shareWhatsApp(){try{const text=await buildWhatsAppReport();window.open('https://wa.me/?text='+encodeURIComponent(text),'_blank','noopener,noreferrer')}catch(e){errorToast(e)}}
$('menuBtn')?.addEventListener('click',()=>$('sidebar').classList.toggle('open'));document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.page)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.go)));document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>closeModal(b.dataset.close)));document.querySelectorAll('.segment').forEach(b=>b.addEventListener('click',()=>{state.selectedType=b.dataset.type;document.querySelectorAll('.segment').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderCategories()}));['search','filterJenis','filterStart','filterEnd'].forEach(id=>$(id)?.addEventListener('input',renderTransactions));document.addEventListener('click',e=>{if(e.target.dataset.edit)openEdit(e.target.dataset.edit);if(e.target.dataset.cancel)openCancel(e.target.dataset.cancel)});
$('transactionForm').addEventListener('reset',()=>setTimeout(()=>{state.selectedType='Pemasukan';document.querySelectorAll('.segment').forEach((x,i)=>x.classList.toggle('active',i===0));renderCategories();setNow()},0));
$('transactionForm').addEventListener('submit',async e=>{e.preventDefault();const b=$('saveBtn');const payload={tanggal:$('tanggal').value,waktu:$('waktu').value,jenis:state.selectedType,kategori:$('kategori').value,nominal:Number($('nominal').value),keterangan:$('keterangan').value.trim(),catatan:$('catatan').value.trim()};if(!payload.nominal||payload.nominal<=0)return toast('Nominal harus lebih besar dari 0.');b.disabled=true;b.innerHTML='⏳ Menyimpan <span>ke database…</span>';try{const r=await KasApi.createTransaction(payload);if(!r?.transaction?.id)throw Error('Server tidak mengembalikan transaksi yang terverifikasi.');const saved=r.transaction;if(saved.status!=='AKTIF'||Number(saved.nominal)!==payload.nominal||saved.jenis!==payload.jenis||saved.keterangan!==payload.keterangan)throw Error('Server menemukan transaksi tetapi datanya tidak cocok. Jangan kirim ulang. ID: '+saved.id);state={...state,...r,transactions:(r.transactions||[]).map(KasApi.normalizeTransaction)};renderDashboard();renderTransactions();e.target.reset();setNow();toast('✓ Tersimpan & diverifikasi di database · '+shortId(saved.id))}catch(err){errorToast(err)}finally{b.disabled=false;b.innerHTML='💾 Simpan ke Database'}});
$('editForm').addEventListener('submit',async e=>{e.preventDefault();try{const c=state.transactions.find(t=>String(t.id)===String($('editId').value));const r=await KasApi.updateTransaction({password:$('editPassword').value,transactionId:$('editId').value,reason:$('editReason').value.trim(),data:{tanggal:$('eTanggal').value,waktu:$('eWaktu').value,jenis:c.jenis,kategori:$('eKategori').value,nominal:Number($('eNominal').value),keterangan:$('eKeterangan').value.trim(),catatan:$('eCatatan').value}});if(!r.writeAcknowledged)throw Error('Server belum mengonfirmasi perubahan.');closeModal('editModal');await reload();toast('✓ Perubahan tersimpan & diverifikasi di database.')}catch(err){errorToast(err)}});
$('cancelForm').addEventListener('submit',async e=>{e.preventDefault();try{const r=await KasApi.cancelTransaction({password:$('cancelPassword').value,transactionId:$('cancelId').value,reason:$('cancelReason').value.trim()});if(!r.writeAcknowledged)throw Error('Server belum mengonfirmasi pembatalan.');closeModal('cancelModal');await reload();toast('✓ Pembatalan tersimpan di database.')}catch(err){errorToast(err)}});
$('configForm').addEventListener('submit',async e=>{e.preventDefault();const password=prompt('Masukkan password admin:');if(!password)return;try{const r=await KasApi.updateConfig({password,config:{nama_rt:$('admin_rt').value,nama_rw:$('admin_rw').value,dukuh:$('admin_dukuh').value,desa:$('admin_desa').value,kecamatan:$('admin_kecamatan').value,kabupaten:$('admin_kabupaten').value,ketua_rt:$('admin_ketua').value,bendahara:$('admin_bendahara').value,saldo_awal:Number($('admin_saldo').value||0)}});if(!r.writeAcknowledged)throw Error('Server belum mengonfirmasi pengaturan.');await reload();toast('✓ Pengaturan tersimpan di database.')}catch(err){errorToast(err)}});
$('passwordForm').addEventListener('submit',async e=>{e.preventDefault();if($('newPassword').value!==$('confirmPassword').value)return toast('Password baru tidak sama.');try{const r=await KasApi.changePassword({currentPassword:$('oldPassword').value,newPassword:$('newPassword').value});if(!r.writeAcknowledged)throw Error('Server belum mengonfirmasi perubahan password.');toast('✓ Password tersimpan di backend.');e.target.reset()}catch(err){errorToast(err)}});
$('pdfBtn').addEventListener('click',async()=>{try{const r=await KasApi.exportReport({startDate:$('reportStart').value,endDate:$('reportEnd').value});$('reportResult').innerHTML=`Laporan siap: <a href="${esc(r.url||'#')}" target="_blank">Buka PDF</a>`}catch(e){errorToast(e)}});
$('waBtn').addEventListener('click',shareWhatsApp);
setNow();load();