/* KAS RT 01 / RW 01 - Google Apps Script backend */
const DB_ID='1bjH08HdZwb7de7tsFe_uZpBY5NvlR8UC8rBr1yVq-ng';
const DEFAULT_PASSWORD='RT01@2026';
const TZ='Asia/Jakarta';
const SHEETS={TRANSAKSI:'TRANSAKSI',CONFIG:'CONFIG',KATEGORI:'KATEGORI',AUDIT:'AUDIT_LOG'};
const HEADERS=['ID','Timestamp','Tanggal','Waktu','Jenis','Kategori','Nominal','Keterangan','Catatan','Status','BuktiURL','UpdatedAt'];
const AUDIT_HEADERS=['Timestamp','Action','TransactionID','Reason','Actor','BeforeJSON','AfterJSON'];
const CATS={Pemasukan:['Iuran Warga','Sumbangan','Bantuan','Donasi','Pendapatan Kegiatan','Lainnya'],Pengeluaran:['Kebersihan','Keamanan','Kegiatan Warga','Sosial','Perbaikan Fasilitas','Listrik','Administrasi','Konsumsi','Bantuan Warga','Lainnya']};

function doGet(e){try{ensureSetup_();const a=String(e&&e.parameter&&e.parameter.action||'health');return json_(route_(a,e&&e.parameter||{}));}catch(x){return json_({success:false,message:x.message});}}
function doPost(e){try{ensureSetup_();const p=parse_(e);const a=String(p.action||e&&e.parameter&&e.parameter.action||'');if(!a)throw Error('Action tidak ditemukan.');return json_(route_(a,p));}catch(x){return json_({success:false,message:x.message});}}
function route_(a,p){switch(a){case'health':return health_();case'initialData':return initialData_();case'transactions':return{success:true,transactions:getTransactions_().map(normalize_)};case'createTransaction':return create_(p);case'updateTransaction':return update_(p);case'cancelTransaction':return cancel_(p);case'updateConfig':return config_(p);case'changePassword':return password_(p);case'exportReport':return export_(p);case'reportSummary':return report_();case'diagnostic':return diagnostic_();default:throw Error('Action tidak dikenali: '+a);}}
function setupApp(){ensureSetup_();Logger.log('SETUP SELESAI: '+ss_().getUrl());}
function ensureSetup_(){const s=ss_();sheet_(SHEETS.TRANSAKSI,HEADERS);sheet_(SHEETS.CONFIG,['Key','Value']);sheet_(SHEETS.KATEGORI,['Jenis','Kategori']);sheet_(SHEETS.AUDIT,AUDIT_HEADERS);const p=PropertiesService.getScriptProperties();if(!p.getProperty('SPREADSHEET_ID'))p.setProperty('SPREADSHEET_ID',DB_ID);if(!p.getProperty('ADMIN_PASSWORD_HASH'))p.setProperty('ADMIN_PASSWORD_HASH',hash_(DEFAULT_PASSWORD));const c=readConfig_();const d={nama_rt:'RT 01',nama_rw:'RW 01',dukuh:'Dukuh Gudang',desa:'Desa Surorejan',kecamatan:'Kecamatan Puring',kabupaten:'Kabupaten Kebumen',ketua_rt:'',bendahara:'',saldo_awal:'0',next_transaction_no:'1'};Object.keys(d).forEach(k=>{if(!(k in c))setConfig_(k,d[k]);});const k=ss_().getSheetByName(SHEETS.KATEGORI);if(k.getLastRow()<2){const r=[];Object.keys(CATS).forEach(j=>CATS[j].forEach(x=>r.push([j,x])));k.getRange(2,1,r.length,2).setValues(r);}}
function health_(){return{success:true,status:'OK',app:'Kas RT 01 / RW 01',time:new Date().toISOString()};}
function initialData_(){return{success:true,config:readConfig_(),categories:readCategories_(),transactions:getTransactions_().map(normalize_),dashboard:dashboard_()};}
function dashboard_(){const c=readConfig_(),t=getTransactions_();let in_=0,out=0,n=0;t.forEach(x=>{if(normalizeStatus_(x.Status)!=='AKTIF')return;const v=parseMoney_(x.Nominal);if(normalizeType_(x.Jenis)==='Pemasukan')in_+=v;else if(normalizeType_(x.Jenis)==='Pengeluaran')out+=v;n++;});const awal=parseMoney_(c.saldo_awal);return{saldoAwal:awal,pemasukan:in_,pengeluaran:out,saldo:awal+in_-out,jumlahTransaksi:n};}
function report_(){const c=readConfig_(),d=dashboard_();return{success:true,date:Utilities.formatDate(new Date(),TZ,'d/M/yyyy'),nama_rt:c.nama_rt||'RT 01',nama_rw:c.nama_rw||'RW 01',dukuh:c.dukuh||'Dukuh Gudang',desa:c.desa||'Desa Surorejan',saldoAwal:d.saldoAwal,pemasukan:d.pemasukan,pengeluaran:d.pengeluaran,saldo:d.saldo};}
function diagnostic_(){const t=getTransactions_(),d=dashboard_();return{success:true,spreadsheetId:DB_ID,rows:t.length,active:t.filter(x=>normalizeStatus_(x.Status)==='AKTIF').length,pemasukan:d.pemasukan,pengeluaran:d.pengeluaran,saldoAwal:d.saldoAwal,saldo:d.saldo,sample:t.slice(0,10).map(normalize_)};}
function create_(p){const jenis=normalizeType_(p.jenis);if(!['Pemasukan','Pengeluaran'].includes(jenis))throw Error('Jenis transaksi tidak valid.');const nominal=parseMoney_(p.nominal);if(!Number.isFinite(nominal)||nominal<=0)throw Error('Nominal harus lebih besar dari 0.');if(!p.tanggal||!p.waktu||!p.kategori||!p.keterangan)throw Error('Tanggal, waktu, kategori, dan keterangan wajib diisi.');const lock=LockService.getScriptLock();lock.waitLock(10000);let id;try{id=nextId_();const now=new Date();const row=[id,now,String(p.tanggal),String(p.waktu),jenis,String(p.kategori),nominal,String(p.keterangan),String(p.catatan||''),'AKTIF',String(p.buktiUrl||''),now];ss_().getSheetByName(SHEETS.TRANSAKSI).appendRow(row);SpreadsheetApp.flush();audit_('CREATE',id,'',{},obj_(row));}finally{lock.releaseLock();}const tx=find_(id);const d=dashboard_();return{success:true,message:'Transaksi berhasil disimpan di database.',id,transaction:normalize_(tx.object),dashboard:d};}
function nextId_(){const c=readConfig_();let n=parseInt(c.next_transaction_no||'1',10);if(!Number.isFinite(n)||n<1)n=1;setConfig_('next_transaction_no',String(n+1));return'TRX-'+String(n).padStart(5,'0');}
function update_(p){auth_(p.password);if(!p.transactionId||!p.reason)throw Error('ID transaksi dan alasan perubahan wajib diisi.');const f=find_(p.transactionId);if(!f)throw Error('Transaksi tidak ditemukan.');const b=f.object;if(normalizeStatus_(b.Status)!=='AKTIF')throw Error('Transaksi yang sudah dibatalkan tidak dapat diedit.');const d=p.data||{},v=parseMoney_(d.nominal);if(!Number.isFinite(v)||v<=0)throw Error('Nominal tidak valid.');const a=Object.assign({},b,{Tanggal:String(d.tanggal||b.Tanggal),Waktu:String(d.waktu||b.Waktu),Jenis:normalizeType_(d.jenis||b.Jenis),Kategori:String(d.kategori||b.Kategori),Nominal:v,Keterangan:String(d.keterangan||b.Keterangan),Catatan:String(d.catatan??b.Catatan),UpdatedAt:new Date()});f.sheet.getRange(f.row,1,1,HEADERS.length).setValues([HEADERS.map(h=>a[h]??'')]);audit_('UPDATE',p.transactionId,p.reason,b,a);SpreadsheetApp.flush();return{success:true,message:'Transaksi berhasil diperbarui di database.',transaction:normalize_(find_(p.transactionId).object),dashboard:dashboard_()};}
function cancel_(p){auth_(p.password);if(!p.transactionId||!p.reason)throw Error('ID transaksi dan alasan pembatalan wajib diisi.');const f=find_(p.transactionId);if(!f)throw Error('Transaksi tidak ditemukan.');const b=f.object;if(normalizeStatus_(b.Status)!=='AKTIF')throw Error('Transaksi sudah dibatalkan.');f.sheet.getRange(f.row,10).setValue('DIBATALKAN');f.sheet.getRange(f.row,12).setValue(new Date());const a=Object.assign({},b,{Status:'DIBATALKAN',UpdatedAt:new Date()});audit_('CANCEL',p.transactionId,p.reason,b,a);SpreadsheetApp.flush();return{success:true,message:'Transaksi dibatalkan.',transaction:normalize_(find_(p.transactionId).object),dashboard:dashboard_()};}
function config_(p){auth_(p.password);const c=p.config||{};Object.keys(c).forEach(k=>setConfig_(k,c[k]));audit_('CONFIG','','Perubahan pengaturan',{},c);SpreadsheetApp.flush();return{success:true,message:'Pengaturan berhasil disimpan di database.',config:readConfig_(),dashboard:dashboard_()};}
function password_(p){auth_(p.currentPassword);const n=String(p.newPassword||'');if(n.length<8)throw Error('Password baru minimal 8 karakter.');PropertiesService.getScriptProperties().setProperty('ADMIN_PASSWORD_HASH',hash_(n));audit_('PASSWORD','','Ganti password',{},{});return{success:true,message:'Password berhasil diganti.'};}
function export_(p){const start=String(p.startDate||''),end=String(p.endDate||'');const tx=getTransactions_().filter(x=>normalizeStatus_(x.Status)==='AKTIF'&&(!start||x.Tanggal>=start)&&(!end||x.Tanggal<=end));const c=readConfig_();let i=0,o=0;tx.forEach(x=>normalizeType_(x.Jenis)==='Pemasukan'?i+=parseMoney_(x.Nominal):o+=parseMoney_(x.Nominal));const doc=DocumentApp.create('Laporan Kas RT '+(start||'awal')+' - '+(end||'sekarang')),b=doc.getBody();b.appendParagraph((c.nama_rt||'RT 01')+' / '+(c.nama_rw||'RW 01')).setHeading(DocumentApp.ParagraphHeading.TITLE);b.appendParagraph([c.dukuh,c.desa,c.kecamatan,c.kabupaten].filter(Boolean).join(' · '));b.appendParagraph('Saldo Awal: Rp '+money_(parseMoney_(c.saldo_awal)));b.appendParagraph('Pemasukan: Rp '+money_(i));b.appendParagraph('Pengeluaran: Rp '+money_(o));b.appendParagraph('Saldo Sekarang: Rp '+money_(parseMoney_(c.saldo_awal)+i-o));const table=[['ID','Tanggal','Jenis','Kategori','Keterangan','Nominal']];tx.slice().reverse().forEach(x=>table.push([x.ID,x.Tanggal,normalizeType_(x.Jenis),x.Kategori,x.Keterangan,'Rp '+money_(parseMoney_(x.Nominal))]));if(table.length>1)b.appendTable(table);doc.saveAndClose();const f=getReportFolder_().createFile(DriveApp.getFileById(doc.getId()).getAs(MimeType.PDF)).setName(doc.getName()+'.pdf');DriveApp.getFileById(doc.getId()).setTrashed(true);return{success:true,url:f.getUrl(),fileId:f.getId(),name:f.getName()};}
function getTransactions_(){const s=ss_().getSheetByName(SHEETS.TRANSAKSI);if(s.getLastRow()<2)return[];const v=s.getRange(1,1,s.getLastRow(),Math.max(s.getLastColumn(),HEADERS.length)).getValues(),h=v.shift().map(String);return v.map(r=>{const o={};h.forEach((x,i)=>o[x]=serialize_(r[i],x));return o}).filter(x=>x.ID).reverse();}
function find_(id){const s=ss_().getSheetByName(SHEETS.TRANSAKSI),n=s.getLastRow();if(n<2)return null;const v=s.getRange(2,1,n-1,HEADERS.length).getValues();for(let i=0;i<v.length;i++)if(String(v[i][0])===String(id))return{sheet:s,row:i+2,object:obj_(v[i])};return null;}
function normalize_(x){return{id:String(x.ID||''),timestamp:x.Timestamp||'',tanggal:String(x.Tanggal||''),waktu:String(x.Waktu||''),jenis:normalizeType_(x.Jenis),kategori:String(x.Kategori||''),nominal:parseMoney_(x.Nominal),keterangan:String(x.Keterangan||''),catatan:String(x.Catatan||''),status:normalizeStatus_(x.Status),buktiUrl:String(x.BuktiURL||''),updatedAt:x.UpdatedAt||''};}
function normalizeStatus_(v){return String(v??'').trim().toUpperCase().replace(/\s+/g,' ');}
function normalizeType_(v){const s=String(v??'').trim().toLowerCase();if(s==='pemasukan')return'Pemasukan';if(s==='pengeluaran')return'Pengeluaran';return String(v??'').trim();}
function parseMoney_(v){if(typeof v==='number')return v;if(v===null||v===undefined||v==='')return 0;let s=String(v).trim().replace(/[^0-9,.-]/g,'');if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.');else if(s.includes('.'))s=s.replace(/\./g,'');else if(s.includes(','))s=s.replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0;}
function obj_(r){const o={};HEADERS.forEach((h,i)=>o[h]=serialize_(r[i],h));return o;}
function readConfig_(){const s=ss_().getSheetByName(SHEETS.CONFIG),o={};if(s.getLastRow()<2)return o;s.getRange(2,1,s.getLastRow()-1,2).getValues().forEach(r=>{if(r[0])o[String(r[0])]=r[1]});return o;}
function setConfig_(k,v){const s=ss_().getSheetByName(SHEETS.CONFIG),n=s.getLastRow();if(n>=2){const vls=s.getRange(2,1,n-1,1).getValues();for(let i=0;i<vls.length;i++)if(String(vls[i][0])===String(k)){s.getRange(i+2,2).setValue(v);return;}}s.appendRow([k,v]);}
function readCategories_(){const s=ss_().getSheetByName(SHEETS.KATEGORI),o={Pemasukan:[],Pengeluaran:[]};if(s.getLastRow()<2)return o;s.getRange(2,1,s.getLastRow()-1,2).getValues().forEach(r=>{if(o[r[0]])o[r[0]].push(String(r[1]))});return o;}
function audit_(a,id,r,b,af){ss_().getSheetByName(SHEETS.AUDIT).appendRow([new Date(),a,id,r,'admin',JSON.stringify(b),JSON.stringify(af)]);}
function auth_(p){if(!p||hash_(String(p))!==PropertiesService.getScriptProperties().getProperty('ADMIN_PASSWORD_HASH'))throw Error('Password admin salah.');}
function hash_(s){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(s),Utilities.Charset.UTF_8).map(b=>(b<0?b+256:b).toString(16).padStart(2,'0')).join('');}
function parse_(e){if(!e||!e.postData||!e.postData.contents)return{};try{return JSON.parse(e.postData.contents)}catch(_){const o={};e.postData.contents.split('&').forEach(x=>{const a=x.split('=');if(a[0])o[decodeURIComponent(a[0])]=decodeURIComponent(a.slice(1).join('='))});return o;}}
function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function ss_(){return SpreadsheetApp.openById(DB_ID)}
function sheet_(n,h){let s=ss_().getSheetByName(n);if(!s)s=ss_().insertSheet(n);if(s.getLastRow()===0)s.getRange(1,1,1,h.length).setValues([h]);return s}
function serialize_(v,h){if(v instanceof Date)return Utilities.formatDate(v,TZ,h==='Tanggal'?'yyyy-MM-dd':h==='Waktu'?'HH:mm':'yyyy-MM-dd HH:mm:ss');return v}
function money_(n){return Number(n||0).toLocaleString('id-ID')}
function getReportFolder_(){const p=PropertiesService.getScriptProperties(),id=p.getProperty('REPORT_FOLDER_ID');if(id){try{return DriveApp.getFolderById(id)}catch(_){}}const f=DriveApp.createFolder('Kas RT 01 - Laporan');p.setProperty('REPORT_FOLDER_ID',f.getId());return f}
