/* KAS RT 01 / RW 01 - Google Apps Script backend */
const DB_ID='1bjH08HdZwb7de7tsFe_uZpBY5NvlR8UC8rBr1yVq-ng',TZ='Asia/Jakarta',DEFAULT_PASSWORD='RT01@2026';
const SHEETS={TRANSAKSI:'TRANSAKSI',CONFIG:'CONFIG',KATEGORI:'KATEGORI',AUDIT:'AUDIT_LOG'};
const HEADERS=['ID','Timestamp','Tanggal','Waktu','Jenis','Kategori','Nominal','Keterangan','Catatan','Status','BuktiURL','UpdatedAt'];
const CATS={Pemasukan:['Iuran Warga','Sumbangan','Bantuan','Donasi','Pendapatan Kegiatan','Lainnya'],Pengeluaran:['Kebersihan','Keamanan','Kegiatan Warga','Sosial','Perbaikan Fasilitas','Listrik','Administrasi','Konsumsi','Bantuan Warga','Lainnya']};
function doGet(e){try{ensure_();return json_(route_(String(e?.parameter?.action||'health'),e?.parameter||{}));}catch(x){return json_({success:false,message:x.message});}}
function doPost(e){try{ensure_();const p=parse_(e),a=String(p.action||e?.parameter?.action||'');if(!a)throw Error('Action tidak ditemukan.');return json_(route_(a,p));}catch(x){return json_({success:false,message:x.message});}}
function route_(a,p){switch(a){case'health':return health_();case'initialData':return initial_();case'transactions':return{success:true,transactions:getTx_().map(norm_)};case'diagnostic':return diagnostic_();case'reportSummary':return report_();case'createTransaction':return create_(p);case'updateTransaction':return update_(p);case'cancelTransaction':return cancel_(p);case'updateConfig':return config_(p);case'changePassword':return changePass_(p);default:throw Error('Action tidak dikenali: '+a);}}
function setupApp(){ensure_();Logger.log('SETUP SELESAI '+ss_().getUrl());}
function ensure_(){const s=ss_();ensureSheet_(SHEETS.TRANSAKSI,HEADERS);ensureSheet_(SHEETS.CONFIG,['Key','Value']);ensureSheet_(SHEETS.KATEGORI,['Jenis','Kategori']);ensureSheet_(SHEETS.AUDIT,['Timestamp','Action','TransactionID','Reason','Actor','BeforeJSON','AfterJSON']);const p=PropertiesService.getScriptProperties();p.setProperty('SPREADSHEET_ID',DB_ID);if(!p.getProperty('ADMIN_PASSWORD_HASH'))p.setProperty('ADMIN_PASSWORD_HASH',hash_(DEFAULT_PASSWORD));const c=readConfig_(),d={nama_rt:'RT 01',nama_rw:'RW 01',dukuh:'Dukuh Gudang',desa:'Desa Surorejan',kecamatan:'Kecamatan Puring',kabupaten:'Kabupaten Kebumen',ketua_rt:'',bendahara:'',saldo_awal:'0',next_transaction_no:'1'};Object.keys(d).forEach(k=>{if(!(k in c))setConfig_(k,d[k])});const k=s.getSheetByName(SHEETS.KATEGORI);if(k.getLastRow()<2){const a=[];Object.keys(CATS).forEach(j=>CATS[j].forEach(x=>a.push([j,x])));k.getRange(2,1,a.length,2).setValues(a)}}
function health_(){return{success:true,status:'OK',app:'Kas RT 01 / RW 01',time:new Date().toISOString()}}
function initial_(){return{success:true,config:readConfig_(),categories:readCats_(),transactions:getTx_().map(norm_),dashboard:dashboard_()}}
function dashboard_(){let i=0,o=0,n=0;getTx_().forEach(x=>{if(normStatus_(x.Status)!=='AKTIF')return;const v=moneyNum_(x.Nominal),j=normType_(x.Jenis);if(j==='Pemasukan')i+=v;else if(j==='Pengeluaran')o+=v;n++});const awal=moneyNum_(readConfig_().saldo_awal);return{saldoAwal:awal,pemasukan:i,pengeluaran:o,saldo:awal+i-o,jumlahTransaksi:n}}
function diagnostic_(){const t=getTx_(),d=dashboard_();return{success:true,spreadsheetId:DB_ID,rows:t.length,active:t.filter(x=>normStatus_(x.Status)==='AKTIF').length,pemasukan:d.pemasukan,pengeluaran:d.pengeluaran,saldoAwal:d.saldoAwal,saldo:d.saldo,headers:headerMap_(),sample:t.slice(0,10).map(norm_)}}
function report_(){const c=readConfig_(),d=dashboard_();return{success:true,date:Utilities.formatDate(new Date(),TZ,'d/M/yyyy'),nama_rt:c.nama_rt||'RT 01',nama_rw:c.nama_rw||'RW 01',dukuh:c.dukuh||'Dukuh Gudang',desa:c.desa||'Desa Surorejan',saldoAwal:d.saldoAwal,pemasukan:d.pemasukan,pengeluaran:d.pengeluaran,saldo:d.saldo}}
function headerMap_(){const s=ss_().getSheetByName(SHEETS.TRANSAKSI),h=s.getRange(1,1,1,s.getLastColumn()).getValues()[0].map(x=>String(x).trim()),m={};h.forEach((x,i)=>{if(x)m[x]=i+1});return m}
function getTx_(){const s=ss_().getSheetByName(SHEETS.TRANSAKSI),last=s.getLastRow(),cols=s.getLastColumn();if(last<2)return[];const h=s.getRange(1,1,1,cols).getValues()[0].map(x=>String(x).trim()),v=s.getRange(2,1,last-1,cols).getValues();return v.map(r=>{const o={};h.forEach((x,i)=>{if(x)o[x]=ser_(r[i],x)});return o}).filter(x=>x.ID).reverse()}
function create_(p){const j=normType_(p.jenis),v=moneyNum_(p.nominal);if(!['Pemasukan','Pengeluaran'].includes(j))throw Error('Jenis transaksi tidak valid.');if(!Number.isFinite(v)||v<=0)throw Error('Nominal harus lebih besar dari 0.');if(!p.tanggal||!p.waktu||!p.kategori||!p.keterangan)throw Error('Tanggal, waktu, kategori, dan keterangan wajib diisi.');const lock=LockService.getScriptLock();lock.waitLock(10000);let id;try{id=nextId_();const now=new Date(),o={ID:id,Timestamp:now,Tanggal:String(p.tanggal),Waktu:String(p.waktu),Jenis:j,Kategori:String(p.kategori),Nominal:v,Keterangan:String(p.keterangan),Catatan:String(p.catatan||''),Status:'AKTIF',BuktiURL:String(p.buktiUrl||''),UpdatedAt:now};appendObject_(o);SpreadsheetApp.flush();audit_('CREATE',id,'',{},o)}finally{lock.releaseLock()}return{success:true,message:'Transaksi berhasil disimpan di database.',id,transaction:norm_(find_(id).object),dashboard:dashboard_()}}
function nextId_(){const c=readConfig_();let n=parseInt(c.next_transaction_no||'1',10);if(!Number.isFinite(n)||n<1)n=1;setConfig_('next_transaction_no',String(n+1));return'TRX-'+String(n).padStart(5,'0')}
function appendObject_(o){const s=ss_().getSheetByName(SHEETS.TRANSAKSI),m=headerMap_(),cols=s.getLastColumn(),row=new Array(cols).fill('');Object.keys(o).forEach(k=>{if(m[k])row[m[k]-1]=o[k]});s.appendRow(row)}
function find_(id){const s=ss_().getSheetByName(SHEETS.TRANSAKSI),n=s.getLastRow(),m=headerMap_();if(n<2||!m.ID)return null;const vals=s.getRange(2,m.ID,n-1,1).getValues();for(let i=0;i<vals.length;i++)if(String(vals[i][0])===String(id)){const r=i+2,cols=s.getLastColumn(),h=s.getRange(1,1,1,cols).getValues()[0].map(x=>String(x).trim()),v=s.getRange(r,1,1,cols).getValues()[0],o={};h.forEach((x,k)=>{if(x)o[x]=ser_(v[k],x)});return{sheet:s,row:r,object:o}}return null}
function update_(p){auth_(p.password);if(!p.transactionId||!p.reason)throw Error('ID transaksi dan alasan perubahan wajib diisi.');const f=find_(p.transactionId);if(!f)throw Error('Transaksi tidak ditemukan.');if(normStatus_(f.object.Status)!=='AKTIF')throw Error('Transaksi yang sudah dibatalkan tidak dapat diedit.');const d=p.data||{},v=moneyNum_(d.nominal);if(!Number.isFinite(v)||v<=0)throw Error('Nominal tidak valid.');const a=Object.assign({},f.object,{Tanggal:String(d.tanggal||f.object.Tanggal),Waktu:String(d.waktu||f.object.Waktu),Jenis:normType_(d.jenis||f.object.Jenis),Kategori:String(d.kategori||f.object.Kategori),Nominal:v,Keterangan:String(d.keterangan||f.object.Keterangan),Catatan:String(d.catatan??f.object.Catatan),UpdatedAt:new Date()});writeObject_(f.row,a);audit_('UPDATE',p.transactionId,p.reason,f.object,a);SpreadsheetApp.flush();return{success:true,message:'Transaksi berhasil diperbarui di database.',transaction:norm_(find_(p.transactionId).object),dashboard:dashboard_()}}
function cancel_(p){auth_(p.password);if(!p.transactionId||!p.reason)throw Error('ID transaksi dan alasan pembatalan wajib diisi.');const f=find_(p.transactionId);if(!f)throw Error('Transaksi tidak ditemukan.');if(normStatus_(f.object.Status)!=='AKTIF')throw Error('Transaksi sudah dibatalkan.');const a=Object.assign({},f.object,{Status:'DIBATALKAN',UpdatedAt:new Date()});writeObject_(f.row,a);audit_('CANCEL',p.transactionId,p.reason,f.object,a);SpreadsheetApp.flush();return{success:true,message:'Transaksi dibatalkan.',transaction:norm_(find_(p.transactionId).object),dashboard:dashboard_()}}
function writeObject_(row,o){const s=ss_().getSheetByName(SHEETS.TRANSAKSI),m=headerMap_();Object.keys(o).forEach(k=>{if(m[k])s.getRange(row,m[k]).setValue(o[k])})}
function config_(p){auth_(p.password);Object.keys(p.config||{}).forEach(k=>setConfig_(k,p.config[k]));SpreadsheetApp.flush();return{success:true,message:'Pengaturan berhasil disimpan.',config:readConfig_(),dashboard:dashboard_()}}
function changePass_(p){auth_(p.currentPassword);const n=String(p.newPassword||'');if(n.length<8)throw Error('Password baru minimal 8 karakter.');PropertiesService.getScriptProperties().setProperty('ADMIN_PASSWORD_HASH',hash_(n));return{success:true,message:'Password berhasil diganti.'}}
function norm_(x){return{id:String(x.ID||''),timestamp:x.Timestamp||'',tanggal:String(x.Tanggal||''),waktu:String(x.Waktu||''),jenis:normType_(x.Jenis),kategori:String(x.Kategori||''),nominal:moneyNum_(x.Nominal),keterangan:String(x.Keterangan||''),catatan:String(x.Catatan||''),status:normStatus_(x.Status),buktiUrl:String(x.BuktiURL||''),updatedAt:x.UpdatedAt||''}}
function normStatus_(v){return String(v??'').trim().toUpperCase().replace(/\s+/g,' ')}
function normType_(v){const s=String(v??'').trim().toLowerCase();return s==='pemasukan'?'Pemasukan':s==='pengeluaran'?'Pengeluaran':String(v??'').trim()}
function moneyNum_(v){if(typeof v==='number')return v;if(v==null||v==='')return 0;let s=String(v).trim().replace(/[^0-9,.-]/g,'');if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.');else if(s.includes('.'))s=s.replace(/\./g,'');else if(s.includes(','))s=s.replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0}
function readConfig_(){const s=ss_().getSheetByName(SHEETS.CONFIG),o={};if(s.getLastRow()<2)return o;s.getRange(2,1,s.getLastRow()-1,2).getValues().forEach(r=>{if(r[0])o[String(r[0])]=r[1]});return o}
function setConfig_(k,v){const s=ss_().getSheetByName(SHEETS.CONFIG),n=s.getLastRow();if(n>=2){const a=s.getRange(2,1,n-1,1).getValues();for(let i=0;i<a.length;i++)if(String(a[i][0])===String(k)){s.getRange(i+2,2).setValue(v);return}}s.appendRow([k,v])}
function readCats_(){const s=ss_().getSheetByName(SHEETS.KATEGORI),o={Pemasukan:[],Pengeluaran:[]};if(s.getLastRow()<2)return o;s.getRange(2,1,s.getLastRow()-1,2).getValues().forEach(r=>{if(o[r[0]])o[r[0]].push(String(r[1]))});return o}
function audit_(a,id,r,b,af){ss_().getSheetByName(SHEETS.AUDIT).appendRow([new Date(),a,id,r,'admin',JSON.stringify(b),JSON.stringify(af)])}
function auth_(p){if(!p||hash_(String(p))!==PropertiesService.getScriptProperties().getProperty('ADMIN_PASSWORD_HASH'))throw Error('Password admin salah.')}
function hash_(s){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(s),Utilities.Charset.UTF_8).map(b=>(b<0?b+256:b).toString(16).padStart(2,'0')).join('')}
function parse_(e){if(!e?.postData?.contents)return{};try{const j=JSON.parse(e.postData.contents);if(j.payload&&typeof j.payload==='string')return JSON.parse(j.payload);return j}catch(_){const o={};e.postData.contents.split('&').forEach(x=>{const a=x.split('=');if(a[0])o[decodeURIComponent(a[0])]=decodeURIComponent(a.slice(1).join('='))});return o}}
function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function ss_(){return SpreadsheetApp.openById(DB_ID)}
function ensureSheet_(n,h){let s=ss_().getSheetByName(n);if(!s)s=ss_().insertSheet(n);if(s.getLastRow()===0)s.getRange(1,1,1,h.length).setValues([h]);return s}
function ser_(v,h){if(v instanceof Date)return Utilities.formatDate(v,TZ,h==='Tanggal'?'yyyy-MM-dd':h==='Waktu'?'HH:mm':'yyyy-MM-dd HH:mm:ss');return v}
