const APP_VERSION='2026.08.20.08';
const DB_ID='1bjH08HdZwb7de7tsFe_uZpBY5NvlR8UC8rBr1yVq-ng';
const TZ='Asia/Jakarta';
const SHEETS={TRANSAKSI:'TRANSAKSI',CONFIG:'CONFIG',KATEGORI:'KATEGORI',AUDIT:'AUDIT_LOG'};
const HEADERS=['ID','Timestamp','Tanggal','Waktu','Jenis','Kategori','Nominal','Keterangan','Catatan','BuktiURL','Status','CreatedBy','UpdatedAt','UpdatedBy'];
function doGet(e){try{setup_();const a=String(e?.parameter?.action||'app');if(a==='app')return HtmlService.createHtmlOutputFromFile('Index').setTitle('Kas RT 01 / RW 01').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);return json_(route_(a,e.parameter||{}));}catch(err){return json_({success:false,message:err.message,stack:String(err.stack||'')});}}
function doPost(e){try{setup_();const p=parse_(e);return json_(route_(p.action||'',p));}catch(err){return json_({success:false,message:err.message,stack:String(err.stack||'')});}}
function initialData(){setup_();return safe_(initial_());}
function createTransaction(p){setup_();return safe_(create_(p||{}));}
function updateTransaction(p){setup_();return safe_(update_(p||{}));}
function cancelTransaction(p){setup_();return safe_(cancel_(p||{}));}
function updateConfig(p){setup_();return safe_(config_(p||{}));}
function changePassword(p){setup_();return safe_(changePassword_(p||{}));}
function reportSummary(){setup_();return safe_(report_());}
function createReportPdf(p){setup_();return safe_(createPdf_(p||{}));}
function diagnostic(){setup_();return safe_(diagnostic_());}
function testBackend(){setup_();return{success:true,version:APP_VERSION,time:Utilities.formatDate(new Date(),TZ,'yyyy-MM-dd HH:mm:ss'),spreadsheetId:DB_ID,sheet:!!ss_().getSheetByName(SHEETS.TRANSAKSI),createFunction:typeof createTransaction==='function'};}
function route_(a,p){switch(a){case'initialData':return initial_();case'createTransaction':return create_(p);case'updateTransaction':return update_(p);case'cancelTransaction':return cancel_(p);case'updateConfig':return config_(p);case'changePassword':return changePassword_(p);case'reportSummary':return report_();case'createReportPdf':return createPdf_(p);case'diagnostic':return diagnostic_();case'testBackend':return testBackend();default:throw Error('Action tidak dikenali: '+a);}}
function safe_(o){return JSON.parse(JSON.stringify(o));}
function setup_(){const s=ss_();sheet_(SHEETS.TRANSAKSI,HEADERS);sheet_(SHEETS.CONFIG,['Key','Value']);sheet_(SHEETS.KATEGORI,['Jenis','Kategori']);sheet_(SHEETS.AUDIT,['Timestamp','Action','TransactionID','Reason','Actor','BeforeJSON','AfterJSON']);const c=readConfig_();if(c.saldo_awal===undefined)setConfig_('saldo_awal','0');if(c.nama_rt===undefined)setConfig_('nama_rt','RT 01');if(c.nama_rw===undefined)setConfig_('nama_rw','RW 01');if(c.dukuh===undefined)setConfig_('dukuh','Dukuh Gudang');if(c.desa===undefined)setConfig_('desa','Surorejan');if(c.kecamatan===undefined)setConfig_('kecamatan','Puring');if(c.kabupaten===undefined)setConfig_('kabupaten','Kebumen');}
function initial_(){return{success:true,version:APP_VERSION,config:readConfig_(),categories:categories_(),transactions:transactions_(),dashboard:dashboard_()};}
function transactions_(){const s=ss_().getSheetByName(SHEETS.TRANSAKSI);if(s.getLastRow()<2)return[];const v=s.getRange(1,1,s.getLastRow(),s.getLastColumn()).getValues(),h=v.shift().map(String);return v.map(r=>{const o={};h.forEach((x,i)=>o[x]=r[i]);return normalize_(o)}).filter(x=>x.id).reverse();}
function normalize_(x){let status=String(x.Status||'').trim().toUpperCase(),bukti=String(x.BuktiURL||'');if(!status&&bukti.toUpperCase()==='AKTIF'){status='AKTIF';bukti='';}return{id:String(x.ID||''),timestamp:date_(x.Timestamp),tanggal:dateOnly_(x.Tanggal),waktu:timeOnly_(x.Waktu),jenis:type_(x.Jenis),kategori:String(x.Kategori||''),nominal:money_(x.Nominal),keterangan:String(x.Keterangan||''),catatan:String(x.Catatan||''),buktiUrl:bukti,status,createdBy:createdBy_(x.CreatedBy),updatedAt:date_(x.UpdatedAt),updatedBy:String(x.UpdatedBy||'')}}
function createdBy_(v){return v instanceof Date?'':String(v||'');}
function dateOnly_(v){return v instanceof Date?Utilities.formatDate(v,TZ,'yyyy-MM-dd'):String(v||'');}
function timeOnly_(v){return v instanceof Date?Utilities.formatDate(v,TZ,'HH:mm'):String(v||'');}
function dashboard_(){const c=readConfig_(),t=transactions_();let i=0,o=0,n=0;t.forEach(x=>{if(x.status!=='AKTIF')return;n++;if(x.jenis==='Pemasukan')i+=x.nominal;if(x.jenis==='Pengeluaran')o+=x.nominal});const awal=money_(c.saldo_awal);return{saldoAwal:awal,pemasukan:i,pengeluaran:o,saldo:awal+i-o,jumlahTransaksi:n};}
function create_(p){const jenis=type_(p.jenis),nominal=money_(p.nominal);if(!['Pemasukan','Pengeluaran'].includes(jenis))throw Error('Jenis transaksi tidak valid.');if(nominal<=0)throw Error('Nominal harus lebih besar dari 0.');if(!p.tanggal||!p.waktu||!p.kategori||!p.keterangan)throw Error('Tanggal, waktu, kategori, dan keterangan wajib diisi.');const lock=LockService.getScriptLock();lock.waitLock(10000);try{const id=nextId_(),now=new Date(),s=ss_().getSheetByName(SHEETS.TRANSAKSI),m=headerMap_(s),row=new Array(Math.max(s.getLastColumn(),HEADERS.length)).fill(''),put=(h,v)=>{if(m[h])row[m[h]-1]=v};put('ID',id);put('Timestamp',now);put('Tanggal',p.tanggal);put('Waktu',p.waktu);put('Jenis',jenis);put('Kategori',p.kategori);put('Nominal',nominal);put('Keterangan',p.keterangan);put('Catatan',p.catatan||'');put('BuktiURL',p.buktiUrl||'');put('Status','AKTIF');put('CreatedBy','admin');put('UpdatedAt',now);put('UpdatedBy','admin');s.getRange(s.getLastRow()+1,1,1,row.length).setValues([row]);SpreadsheetApp.flush();const tx=find_(id);if(!tx||tx.status!=='AKTIF')throw Error('Transaksi gagal diverifikasi setelah disimpan. ID: '+id);return{success:true,version:APP_VERSION,id,transaction:tx,dashboard:dashboard_()};}finally{lock.releaseLock();}}
function nextId_(){const c=readConfig_();let n=parseInt(c.next_transaction_no||'1',10);if(!Number.isFinite(n)||n<1)n=1;setConfig_('next_transaction_no',String(n+1));return'TRX-'+String(n).padStart(5,'0');}
function update_(p){auth_(p.password);const f=findRow_(p.transactionId);if(!f)throw Error('Transaksi tidak ditemukan.');if(f.data.status!=='AKTIF')throw Error('Transaksi sudah dibatalkan.');if(!p.reason)throw Error('Alasan perubahan wajib diisi.');const before=f.data,d=p.data||{},m=headerMap_(f.sheet),row=f.sheet.getRange(f.row,1,1,f.sheet.getLastColumn()).getValues()[0],set=(h,v)=>{if(m[h])row[m[h]-1]=v};set('Tanggal',d.tanggal);set('Waktu',d.waktu);set('Jenis',type_(d.jenis));set('Kategori',d.kategori);set('Nominal',money_(d.nominal));set('Keterangan',d.keterangan);set('Catatan',d.catatan||'');set('UpdatedAt',new Date());set('UpdatedBy','admin');f.sheet.getRange(f.row,1,1,row.length).setValues([row]);SpreadsheetApp.flush();const after=find_(p.transactionId);audit_('UPDATE',p.transactionId,p.reason,before,after);return{success:true,transaction:after,dashboard:dashboard_()};}
function cancel_(p){auth_(p.password);const f=findRow_(p.transactionId);if(!f)throw Error('Transaksi tidak ditemukan.');if(f.data.status!=='AKTIF')throw Error('Transaksi sudah dibatalkan.');if(!p.reason)throw Error('Alasan pembatalan wajib diisi.');const before=f.data,m=headerMap_(f.sheet);f.sheet.getRange(f.row,m.Status).setValue('DIBATALKAN');f.sheet.getRange(f.row,m.UpdatedAt).setValue(new Date());f.sheet.getRange(f.row,m.UpdatedBy).setValue('admin');SpreadsheetApp.flush();const after=find_(p.transactionId);audit_('CANCEL',p.transactionId,p.reason,before,after);return{success:true,transaction:after,dashboard:dashboard_()};}
function config_(p){auth_(p.password);Object.keys(p.config||{}).forEach(k=>setConfig_(k,p.config[k]));SpreadsheetApp.flush();return{success:true,config:readConfig_(),dashboard:dashboard_()};}
function changePassword_(p){auth_(p.currentPassword);if(String(p.newPassword||'').length<8)throw Error('Password minimal 8 karakter.');PropertiesService.getScriptProperties().setProperty('ADMIN_PASSWORD',String(p.newPassword));return{success:true};}
function report_(){const c=readConfig_(),d=dashboard_();return{success:true,date:Utilities.formatDate(new Date(),TZ,'d/M/yyyy'),nama_rt:String(c.nama_rt||''),nama_rw:String(c.nama_rw||''),dukuh:String(c.dukuh||''),desa:String(c.desa||''),kecamatan:String(c.kecamatan||''),kabupaten:String(c.kabupaten||''),saldoAwal:d.saldoAwal,pemasukan:d.pemasukan,pengeluaran:d.pengeluaran,saldo:d.saldo,transactions:transactions_()};}
function createPdf_(p){const r=report_(),period=p.period||('Per Tanggal '+r.date);const doc=DocumentApp.create('Laporan Kas RT '+r.nama_rt+' - '+Utilities.formatDate(new Date(),TZ,'yyyyMMdd-HHmmss'));const body=doc.getBody();body.appendParagraph('LAPORAN KAS '+r.nama_rt+' / '+r.nama_rw).setHeading(DocumentApp.ParagraphHeading.TITLE);body.appendParagraph(r.dukuh+', Desa '+r.desa+', Kecamatan '+r.kecamatan+', Kabupaten '+r.kabupaten);body.appendParagraph(period);body.appendHorizontalRule();body.appendParagraph('Saldo Awal: Rp '+fmt_(r.saldoAwal));body.appendParagraph('Total Pemasukan: Rp '+fmt_(r.pemasukan));body.appendParagraph('Total Pengeluaran: Rp '+fmt_(r.pengeluaran));body.appendParagraph('SISA SALDO SEKARANG: Rp '+fmt_(r.saldo)).setBold(true);body.appendParagraph('');body.appendParagraph('TRANSAKSI AKTIF').setHeading(DocumentApp.ParagraphHeading.HEADING2);const rows=[['ID','Tanggal','Jenis','Kategori','Keterangan','Nominal']];r.transactions.filter(x=>x.status==='AKTIF').forEach(x=>rows.push([x.id,x.tanggal,x.jenis,x.kategori,x.keterangan,(x.jenis==='Pemasukan'?'+ ':'- ')+'Rp '+fmt_(x.nominal)]));body.appendTable(rows);body.appendParagraph('');body.appendParagraph('Dicetak: '+Utilities.formatDate(new Date(),TZ,'dd/MM/yyyy HH:mm:ss'));doc.saveAndClose();const file=DriveApp.getFileById(doc.getId());const pdf=file.getAs(MimeType.PDF);const out=DriveApp.createFile(pdf).setName(doc.getName()+'.pdf');file.setTrashed(true);return{success:true,fileId:out.getId(),fileName:out.getName(),url:out.getUrl(),downloadUrl:'https://drive.google.com/uc?export=download&id='+out.getId()};}
function fmt_(n){return Number(n||0).toLocaleString('id-ID');}
function diagnostic_(){const t=transactions_(),d=dashboard_();return{success:true,version:APP_VERSION,spreadsheetId:DB_ID,rows:t.length,active:t.filter(x=>x.status==='AKTIF').length,pemasukan:d.pemasukan,pengeluaran:d.pengeluaran,saldoAwal:d.saldoAwal,saldo:d.saldo,headers:headerMap_(ss_().getSheetByName(SHEETS.TRANSAKSI)),sample:t.slice(0,10)};}
function find_(id){const f=findRow_(id);return f?f.data:null;}
function findRow_(id){const s=ss_().getSheetByName(SHEETS.TRANSAKSI);if(s.getLastRow()<2)return null;const m=headerMap_(s),ids=s.getRange(2,m.ID,s.getLastRow()-1,1).getValues();for(let i=0;i<ids.length;i++)if(String(ids[i][0])===String(id)){const row=i+2,vals=s.getRange(row,1,1,s.getLastColumn()).getValues()[0],o={};Object.keys(m).forEach(h=>o[h]=vals[m[h]-1]);return{sheet:s,row,data:normalize_(o)}}return null;}
function headerMap_(s){const h=s.getRange(1,1,1,s.getLastColumn()).getValues()[0].map(String),o={};h.forEach((x,i)=>o[x]=i+1);return o;}
function readConfig_(){const s=ss_().getSheetByName(SHEETS.CONFIG),o={};if(s.getLastRow()>1)s.getRange(2,1,s.getLastRow()-1,2).getValues().forEach(r=>{if(r[0])o[String(r[0])]=safeValue_(r[1])});return o;}
function safeValue_(v){return v instanceof Date?Utilities.formatDate(v,TZ,'yyyy-MM-dd HH:mm:ss'):typeof v==='number'||typeof v==='boolean'||typeof v==='string'?v:String(v??'');}
function setConfig_(k,v){const s=ss_().getSheetByName(SHEETS.CONFIG),m=s.getLastRow()>1?s.getRange(2,1,s.getLastRow()-1,1).getValues():[];for(let i=0;i<m.length;i++)if(String(m[i][0])===k){s.getRange(i+2,2).setValue(v);return;}s.appendRow([k,v]);}
function categories_(){const s=ss_().getSheetByName(SHEETS.KATEGORI),o={Pemasukan:[],Pengeluaran:[]};if(s.getLastRow()>1)s.getRange(2,1,s.getLastRow()-1,2).getValues().forEach(r=>{if(o[r[0]])o[r[0]].push(String(r[1]));});return o;}
function audit_(a,id,r,b,af){ss_().getSheetByName(SHEETS.AUDIT).appendRow([new Date(),a,id,r,'admin',JSON.stringify(b),JSON.stringify(af)]);}
function auth_(p){const saved=PropertiesService.getScriptProperties().getProperty('ADMIN_PASSWORD')||'RT01@2026';if(String(p)!==saved)throw Error('Password admin salah.');}
function parse_(e){if(!e?.postData?.contents)return{};try{const p=JSON.parse(e.postData.contents);if(p.payload)return JSON.parse(p.payload);return p;}catch(_){return{}}}
function type_(v){const s=String(v||'').trim().toLowerCase();return s==='pemasukan'?'Pemasukan':s==='pengeluaran'?'Pengeluaran':String(v||'').trim();}
function money_(v){if(typeof v==='number')return v;let s=String(v||'').replace(/[^0-9,.-]/g,'');if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.');else if(s.includes('.'))s=s.replace(/\./g,'');else if(s.includes(','))s=s.replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0;}
function date_(v){return v instanceof Date?Utilities.formatDate(v,TZ,'yyyy-MM-dd HH:mm:ss'):String(v||'');}
function ss_(){return SpreadsheetApp.openById(DB_ID)}
function sheet_(n,h){let s=ss_().getSheetByName(n);if(!s)s=ss_().insertSheet(n);if(s.getLastRow()===0)s.getRange(1,1,1,h.length).setValues([h]);return s;}
function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
